Purpose: 
To test package with a Fun(Procedure) routine inside; called out of scope.

Result: 
The output does matches what is expected: compilation error due to function not existing outside of scope. 